Feature/basic layout
gudzilla/news-page pull request #2
Opened 2024-01-29 12:27 UTC by gudzilla

2024-01-29 14:34 UTC, Muslik commented on main.js
> +// const menuLinks = document.querySelector('#navbarList');
Коммент не нужен, убираем

2024-01-29 14:36 UTC, Muslik commented on style.css
> +  color: var(--logo-color);
Опа, а почему у тебя logo-color вдруг появляется в других местах )
Это должен быть цвет только логотипа.

Поэтому нужно его переименовать:
Например:
```--accent-color```
Теперь он не завязан на один конкретный элемент

2024-01-29 15:22 UTC, Muslik requested changes

2024-01-29 15:22 UTC, Muslik commented on style.css
> +  font-size: 1.15rem;
Все шрифты да и в принципе все размеры стараемся делать кратными 2м. Не нужно делать шрифт 18.4, потому что эти 0.4 никак не учитываются.
Во всем файле нужно исправить

2024-01-29 15:22 UTC, Muslik commented on style.css
> +  font: inherit;
Он и так его наследовать будет же.

2024-01-29 15:22 UTC, Muslik commented on style.css
> +  color: var(--bg-color);
Так это bg-color или color :)
Если ты назвал переменную специфично, то будь добр ее использовать только для background-ов.

Либо менять ее имя.

2024-01-29 15:22 UTC, Muslik commented on style.css
> +    padding-top: 20px;
Неа. У тебя не должен каждый элемент задавать свои границы. У тебя есть блок - footer. У него есть padding внутренний. Сверху справа снизу слева.
И есть два блока. Два блока между собой толкаются margin-ами. А у тебя получается какая то карусель. Нет системности. Хочет верхний блок себя толкнул, хочет нижний блок себя толкнул. В Footer добавятся элементы, придется переписывать css для текущих....

<img width="361" alt="Screenshot 2024-01-29 at 17 48 37" src="https://github.com/gudzilla/news-site.github.io/assets/15676404/29325823-ca7b-4c62-bdf3-6377d65d0f85">

2024-01-29 15:22 UTC, Muslik commented on index.html
> +      <nav class="header__navbar navbar" id="headerNav">
Бургер должен блочить контент. Весь акцент должен смещаться на него. А у тебя акцент и на хедере и на футере и на контенте остается. Мне кажется не должно быть такого что открыт бургер и я могу нажать куда то на страницу.
Меню открылось, все остальное уезжает на второй план. Поэтому убираем наложение хедера и футера поверх меню. Далее остальное контент надо чем то закрыть. Чтобы он перестал быть кликабельным.
Обычно создают просто невидимый блок и кладут рядом с этой менюшкой (блок можно чуть затемнить чтобы было видно что он не кликабельный.

Можно еще рассмотреть вариант full-screen menu:

https://codepen.io/hugolundin/pen/doymMg
https://codepen.io/hallonanton/details/XOVvZv
https://codepen.io/feizc002/pen/bQqqPm
https://codepen.io/victorfreire/pen/QywRNM

2024-01-29 15:22 UTC, Muslik commented on style.css
> +  font-size: 1.8rem;
1. Логотип обычно бывает в одинаковой цветовой гамме. А в футере он у тебя просто часть текста.
2. Тут можно модификаторами обойтись.
```
// Тут указываешь основные стили и размер для логотипа.
// display flex и shrink тоже должен быть тут.
.logo {}

// А тут добавляешь отдельный стили для маленького логотипа.
.logo_small {}
```

.header__logo и footer__logo будут отвечать чисто за отступы. Все font-weight и тд уже в logo пихай. Это готовый блок, они всегда должны быть одинаковыми

Ну и по моему мнению у тебя просто один кусок текста в футере на мобильной версии. Как то сложно понять что там оказывается кликнуть на что то можно

2024-01-29 15:22 UTC, Muslik commented on style.css
> +  height: 3px;
Все размеры кратные 2м должны быть

2024-01-29 15:22 UTC, Muslik commented on style.css
> +    background-color: #121826b8;
Че за цвет? Почему нет в палитре?

2024-02-07 11:10 UTC, gudzilla commented on style.css
> +  font-size: 1.15rem;
То что размеры стараться делать кратными 2м я приму к сведению.

Десятичные части у меня указаны на rem-ах, потому что они там играют роль.
Rem-ы тоже надо кратные двум делать? 
Ведь они как процентное соотношение используются и например уменьшить на 1/4 будет 0.75rem.

И в стилях кнопки мобильной менюшки нельзя менять значения на кратные 2м потому что стили собьются. 
<img width="363" alt="Screenshot 2024-02-07 at 14 00 56" src="https://github.com/gudzilla/news-site.github.io/assets/57419893/17b79e6e-d1dc-4997-92ec-1871d3b18c7c">

2024-02-07 15:30 UTC, gudzilla commented on style.css
> +  font-size: 1.8rem;
1. и 2.
<img width="256" alt="Screenshot 2024-02-07 at 18 25 29" src="https://github.com/gudzilla/news-site.github.io/assets/57419893/dd23b6a5-376c-4908-bdbc-a51d7a98850a">
<img width="234" alt="Screenshot 2024-02-07 at 18 25 41" src="https://github.com/gudzilla/news-site.github.io/assets/57419893/a30b0843-b02f-49da-8970-26ec115c2289">

Сделал более очевидным что в футере ссылки

2024-02-07 15:32 UTC, gudzilla commented on style.css
> +  height: 3px;
Тут иконка меню по пикселям рассчитана. Изменить на пиксель и она после анимации будет кривой

2024-02-08 05:30 UTC, gudzilla commented on style.css
> +    padding-top: 20px;
Убрал лишние падинги и создал расстояние между блоками флексами.
<img width="369" alt="Screenshot 2024-02-08 at 08 30 11" src="https://github.com/gudzilla/news-site.github.io/assets/57419893/96ed5aa9-c100-440a-a39e-5b60f229ae83">

2024-02-08 05:32 UTC, gudzilla commented on style.css
> +  font-size: 1.15rem;
Исправил rem'ы чтобы из них по итогу были целые пиксельные значения кратные 2м.

2024-02-10 16:32 UTC, Muslik approved these changes
С переменными цвета решил не заморачиваться походу ) 
Ну допустим

2024-02-11 12:18 UTC, merged