Created NewsApi for news requests and split js-code into modules
gudzilla/news-page pull request #3
Opened 2024-02-12 10:41 UTC by gudzilla

2024-02-12 19:53 UTC, Muslik requested changes
Есть небольшие замечания

2024-02-12 19:53 UTC, Muslik commented on resources/js/api/newsApi.js
> + * @typedef Sources
Это единственное число. Поэтому `Source`
А вот ниже уже будет массив - `Source[]` - массив сорсов

2024-02-12 19:53 UTC, Muslik commented on resources/js/api/newsApi.js
> +        apiKey: this.#API_KEY,
Тут наверное должно быть `this.#defaultParams`

2024-02-12 19:53 UTC, Muslik commented on resources/js/baseRequest.js
> +    const promise = fetch(`${this.#baseUrl}${url}${queryString}`, {
Сразу `return fetch`. Не нужна отдельная переменная

2024-02-12 19:53 UTC, Muslik commented on resources/js/baseRequest.js
> +    for (const [key, value] of response.headers.entries()) {
Унеси это в отдельную функцию. Это же явно потребовалось бы и в post и в put и тд

2024-02-12 19:53 UTC, Muslik commented on resources/js/baseRequest.js
> +      console.log("Request response is JSON.");
Этого не должно тут быть

2024-02-12 19:53 UTC, Muslik commented on resources/js/baseRequest.js
> +    if (response.headers.get("content-type").includes("application/json")) {
Можно унести также в утилитарную функцию - `#contentIs(headers, "application/json")`

И потом будешь дергать: 
```
if (this.#contentIs(headers, "application/json") {
  // do something
}
```

2024-02-12 19:53 UTC, Muslik commented on resources/js/baseRequest.js
> +      console.log("Request response is NOT JSON!");
Круто ) А дальше че с таким контентом делать? )
body то никуда не делся. Ну и консоль убираем

2024-02-12 19:53 UTC, Muslik commented on resources/js/baseRequest.js
> +
```
  const body = this.#contentIs(response.headers, 'application/json')
    ? await response.json()
    : await response.text();
  ```
  
  И ниже уже собирай объект чем его по частям вверху раскидывать:
  ```
  const responder = {
    ok: response.ok,
    body,
    status: response.status,
    headers: this.#toObject(response.headers)
  }
  ```

2024-02-12 19:53 UTC, Muslik commented on resources/js/baseRequest.js
> +      queryString += queryString === "" ? "?" : "&";
Есть замечательная штука для составления таких строк, которая называется `URLSearchParams`. Заюзай ее для этих манипуляций

2024-02-12 19:57 UTC, Muslik commented
И у тебя конфликты с твоей основной веткой

2024-02-22 15:29 UTC, gudzilla commented on resources/js/api/newsApi.js
> +        apiKey: this.#API_KEY,
В `this.#defaultParams` есть значение `pageSize`, которого не должно быть в параметрах запроса новостных источников. Поэтому я просто передал ключ Api и остальные параметры беру через `...params` (87 строка)

2024-02-22 16:50 UTC, gudzilla commented on resources/js/baseRequest.js
> +    for (const [key, value] of response.headers.entries()) {
<img width="406" alt="Screenshot 2024-02-22 at 19 50 34" src="https://github.com/gudzilla/news-site.github.io/assets/57419893/e84f80ec-8a68-472c-ab99-d2ae0b001e1f">

2024-02-22 16:52 UTC, gudzilla commented on resources/js/baseRequest.js
> +    if (response.headers.get("content-type").includes("application/json")) {
<img width="580" alt="Screenshot 2024-02-22 at 19 51 25" src="https://github.com/gudzilla/news-site.github.io/assets/57419893/0649aaa9-eb26-4398-84fc-379e8718b64e">
<img width="670" alt="Screenshot 2024-02-22 at 19 51 34" src="https://github.com/gudzilla/news-site.github.io/assets/57419893/28455814-6ad1-4e98-b7cb-78bfe9ca73bf">

2024-02-23 16:23 UTC, Muslik requested changes
Нет коммита

2024-02-23 16:25 UTC, Muslik commented on resources/js/baseRequest.js
> +    let queryString2 = new URLSearchParams(params);
Зачем тут let ?
Почему тут queryString2 а не просто queryString

2024-02-23 16:27 UTC, Muslik commented on resources/js/baseRequest.js
> +      headers: toObject(response.headers.entries()),
```
this.#toObject(response.headers) {}
```

2024-02-23 16:28 UTC, Muslik approved these changes
Два замечания маленькие

2024-02-23 16:34 UTC, merged